Generate OLM manifests
stackabletech/stackable-utils pull request #54
Opened 2023-11-02 17:29 UTC by razvan

Fixes https://github.com/stackabletech/stackable-utils/issues/52

2023-11-13 16:10 UTC, adwk67 requested changes

2023-11-13 16:29 UTC, adwk67 commented on olm/build-manifests.sh
> +# * Insert the contents of the deployment, cluster role and service account that are
Ah, I've had another look and seen that you've replaced the in-line cluster permissions with ones covered by the cluster role.

2023-11-13 16:32 UTC, adwk67 commented on olm/build-manifests.sh
> +# * Insert the contents of the deployment, cluster role and service account that are
Maybe we could document this schematically with placeholders: this-bit-goes-here etc.

2023-11-13 16:47 UTC, adwk67 commented on olm/build-manifests.sh
> +# * Check or update the metadata/dependecies.yaml
```suggestion
# * Check or update the metadata/dependencies.yaml
```

2023-11-20 09:20 UTC, razvan commented on olm/build-manifests.sh
> +# The generated manifests need to be updated manually with the following steps:
Done.

2023-11-20 09:21 UTC, razvan commented on olm/build-manifests.sh
> +# * Insert the contents of the deployment, cluster role and service account that are
I tried to clarify things a bit more in the comments. Ideally, we would do these replacements automatically too.

2023-11-20 09:23 UTC, adwk67 commented on olm/build-manifests.sh
> +# * Insert the contents of the deployment, cluster role and service account that are
Thanks!

2023-11-20 10:15 UTC, razvan commented on olm/build-manifests.sh
> +		  com.redhat.openshift.versions: v4.10-v4.11
Updated https://github.com/stackabletech/stackable-utils/pull/54/commits/5a819c6361ca58588cf245d4f99e61bd4a51e5aa

2023-11-20 10:48 UTC, adwk67 approved these changes
LGTM!

2023-11-20 15:17 UTC, merged