combine bugfix script with release-tag scripts; wip - release candidates
stackabletech/stackable-utils pull request #95
Opened 2024-12-02 14:52 UTC by adwk67

2025-01-22 12:05 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
>  	git commit -sam "release $RELEASE_TAG"
Oh, something I have had on my list is to use conventional commit messages for genreated commits.

2025-01-22 12:38 UTC, Techassi commented on release/create-release-candidate-branch.sh
> +	# TODO: jinja2-cli including pyyaml package?
note: We should check that jinja2 exists because the script will exit in a potentially inconsistent state.

2025-01-22 12:38 UTC, NickLarsenNZ requested changes
Looks pretty good, just left a few suggestions.

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
> +		echo "Tag $RELEASE_TAG already exists!"
We can redirect stdout to stderr here, as is conventional.

```suggestion
		>&2 echo "Tag $RELEASE_TAG already exists!"
```

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
>  	git commit -sam "release $RELEASE_TAG"
Oh, also PR titles (which end up as the commit message) once squash-merged.

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
> +	#		echo "Error: Proposed tag $RELEASE_TAG is earlier than existing tag $EXISTING_TAG."
```suggestion
	#		>&2 echo "Error: Proposed tag $RELEASE_TAG is earlier than existing tag $EXISTING_TAG."
```

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
>  		echo "Expected release branch is missing: $RELEASE_BRANCH"
Can we make that `>&2 echo`.

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
> +		echo "PR branch already exists: ${REPOSITORY}/$PR_BRANCH"
```suggestion
		>&2 echo "PR branch already exists: ${REPOSITORY}/$PR_BRANCH"
```

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
>  			echo "Expected release branch is missing: ${operator}/$RELEASE_BRANCH"
Can we make that `>&2 echo`, please?

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
> +			echo "PR branch already exists: ${operator}/$PR_BRANCH"
```suggestion
			>&2 echo "PR branch already exists: ${operator}/$PR_BRANCH"
```

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
> +		echo "Usage: create-release-candidate-branch.sh -t <tag> [-p] [-c] [-w products|operators|all]"
```suggestion
		>&2 echo "Usage: create-release-candidate-branch.sh -t <tag> [-p] [-c] [-w products|operators|all]"
```

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
>  		git commit -sam "release $RELEASE_TAG"
Ideally this message should also be a conventional-commit message.

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
> +		gh pr create --reviewer stackabletech/developers --dry-run --base "${RELEASE_BRANCH}" --head "${PR_BRANCH}" --title "release: ${RELEASE_TAG}" --body "${PR_MSG}"
```suggestion
		gh pr create --reviewer stackabletech/developers --dry-run --base "${RELEASE_BRANCH}" --head "${PR_BRANCH}" --title "chore: Release ${RELEASE_TAG}" --body "${PR_MSG}"
```

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
> +		gh pr create --reviewer stackabletech/developers --base "${RELEASE_BRANCH}" --head "${PR_BRANCH}" --title "release: ${RELEASE_TAG}" --body "${PR_MSG}"
suggestion: Use conventional-commits in PR titles.

```suggestion
		gh pr create --reviewer stackabletech/developers --base "${RELEASE_BRANCH}" --head "${PR_BRANCH}" --title "chore: Release ${RELEASE_TAG}" --body "${PR_MSG}"
```

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
> +		gh pr create --reviewer stackabletech/developers --base "${RELEASE_BRANCH}" --head "${PR_BRANCH}" --title "release: ${RELEASE_TAG}" --body "${PR_MSG}"
Another idea would be to construct these command lines once, and in the dry-run case, just append the `--dry-run` flag (assuming order isn't important).

Something like:

```shell
PUSH_CMD="git push '${REPOSITORY}' '${PR_BRANCH}'"
PR_CMD="gh pr create --reviewer stackabletech/developers --base '${RELEASE_BRANCH}' --head '${PR_BRANCH}' --title 'chore: Release ${RELEASE_TAG}' --body '${PR_MSG}'"

if $PUSH; then
  echo "Pushing changes..."
  bash -c "$PUSH_CMD"
  bash -c "$PR_CMD"
else
  echo "(Dry-run: not pushing...)"
  bash -c "$PUSH_CMD --dry-run"
  bash -c "$PR_CMD --dry-run"
fi
```

> [!NOTE]
> _I used a `bash` here so that shellcheck doesn't complain about executing the variable. Alternatively, you can disable shellcheck for these calls._

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/create-release-candidate-branch.sh
> +
:rocket:

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/README.md
> +# finally - i.e. when a release candidate ahs been accepted and the actual release has been tagged - patch the changelog file in the main branch
```suggestion
# finally - i.e. when a release candidate has been accepted and the actual release has been tagged - patch the changelog file in the main branch
```

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/README.md
> +### N.B.
This could be an admonition...

```suggestion
> [!NOTE]
```

(next comment continues the change)

2025-01-22 12:38 UTC, NickLarsenNZ commented on release/README.md
> +- Any changes should be done manually between steps 2 and 3 i.e. by making changes in the PR branch and/or cherry-picking commits from main.
Continued from the previous comment (about admonitions)

```suggestion
> - Steps 2-4 will check out the release branch (or clone it if does exist locally) and so can be run independently of each other.
> - Any changes should be done manually between steps 2 and 3 i.e. by making changes in the PR branch and/or cherry-picking commits from main.
```

2025-01-22 13:39 UTC, adwk67 commented on release/create-release-candidate-branch.sh
>  			echo "Expected release branch is missing: ${operator}/$RELEASE_BRANCH"
See 81a0aa9

2025-01-22 13:39 UTC, adwk67 commented on release/create-release-candidate-branch.sh
>  		echo "Expected release branch is missing: $RELEASE_BRANCH"
See 81a0aa9

2025-01-22 13:40 UTC, adwk67 commented on release/create-release-candidate-branch.sh
>  	git commit -sam "release $RELEASE_TAG"
See 81a0aa9

2025-01-22 16:40 UTC, adwk67 commented on release/create-release-candidate-branch.sh
> +	# TODO: jinja2-cli including pyyaml package?
See e3f1764

2025-01-22 16:40 UTC, adwk67 commented on release/create-release-candidate-branch.sh
> +	git config --get user.name
See e3f1764

2025-01-23 08:36 UTC, NickLarsenNZ submitted a review, later dismissed
LGTM

2025-01-23 08:50 UTC, Techassi commented on release/create-release-candidate-branch.sh
> +	git config --get user.name
In 5ec621c you print out the git user name and email using this format: `'$git_user/$git_email'`. I feel like we should use the well-established format of `$git_user <$git_email>` instead, eg:

```shell
$ git log -1
commit b8fe43f7368249bf95b06d6cba3fd0135f7523ac (HEAD -> main, tag: stackable-operator-0.84.1, origin/main, origin/HEAD)
Author: Xenia <xeniafischer@hotmail.de>
Date:   Wed Jan 22 14:51:25 2025 +0100
```

2025-01-23 09:09 UTC, adwk67 commented on release/create-release-candidate-branch.sh
> +	git config --get user.name
Done a12abbf

2025-01-23 09:25 UTC, Techassi commented on release/README.md
> +# repeat the above with e.g. the tag 25.3.0 once a release candidate is accepted.
question: Should the `./release/tag-release-candidate.sh` script be used to create a non-rc tag? If so, I think it is a little confusing.

2025-01-23 09:25 UTC, Techassi commented on release/README.md
> +./release/tag-release-candidate.sh -t  25.3.0-rc1 -w products # Only add the -p flag after testing locally first
```suggestion
./release/tag-release-candidate.sh -t 25.3.0-rc1 -w products # Only add the -p flag after testing locally first
```

2025-01-23 09:25 UTC, Techassi commented on release/README.md
> +./release/tag-release-candidate.sh -t  25.3.0-rc1 -w operators # Only add the -p flag after testing locally first
```suggestion
./release/tag-release-candidate.sh -t 25.3.0-rc1 -w operators # Only add the -p flag after testing locally first
```

2025-01-23 09:28 UTC, adwk67 commented on release/README.md
> +# repeat the above with e.g. the tag 25.3.0 once a release candidate is accepted.
This could get philosophical - yes, I see your point, but we have one flow via the testable PR-branches for everything that is pre- or on-the-way-to- release.

2025-01-23 09:32 UTC, adwk67 commented on release/README.md
> +# repeat the above with e.g. the tag 25.3.0 once a release candidate is accepted.
We could call it tag-release.sh I suppose, but the same flow would/could be used for things that are tagged -rcXXX (the original plan). Not sure if that is much an improvement. Hopefully any ambiguitiy is cleared up in the docs, specifically [here](https://github.com/stackabletech/stackable-utils/blob/feature/release-candidates/release/README.md?plain=1#L89-L93)?

2025-01-23 10:10 UTC, Techassi commented on release/README.md
> +# repeat the above with e.g. the tag 25.3.0 once a release candidate is accepted.
Let's leave it as is for now. We still can change this down the line if it annoys us.

2025-01-23 12:53 UTC, NickLarsenNZ approved these changes
LGTM

2025-01-23 12:54 UTC, merged